<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, September 6, 2025 6:13:37 AM</msg><msg code="0" type="0">Preparing inputs…</msg><msg code="1" type="100">﻿Traceback (most recent call last):
﻿  File "&lt;string&gt;", line 101, in execute
﻿  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 20777, in Project
﻿    raise e
﻿  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 20759, in Project
﻿    gp.Project_management(
﻿  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 533, in &lt;lambda&gt;
﻿    return lambda *args: val(*gp_fixargs(args, True))
﻿                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿arcgisscripting.ExecuteError: ERROR 999999: Something unexpected caused the tool to fail. Contact Esri Technical Support (http://esriurl.com/support) to Report a Bug, and refer to the error help for potential solutions or workarounds.
Create output feature class failed
Failed to execute (Project).

</msg><msg code="-2147467259" type="100">Failed to execute (BuildingProximity).</msg><msg code="0" type="3">Failed at Saturday, September 6, 2025 6:13:38 AM (Elapsed Time: 1.53 seconds)</msg></messages>